// <auto-generated />
using System;
using BE_Fan_Fusion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE_Fan_Fusion.Migrations
{
    [DbContext(typeof(FanFusionDbContext))]
    partial class FanFusionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE_Fan_Fusion.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Science Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Supernatural"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Slice of Life"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Historical Fiction"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Humor"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Drama"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Fanfiction"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Crossover"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Fluff"
                        });
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SaveAsDraft")
                        .HasColumnType("boolean");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Harry stood at the entrance to Hogwarts once more, the weight of his past decisions heavy on his mind. This time, he vowed, things would be different. The Sorting Hat sensed his presence even before he entered the Great Hall. ‘Ah, Potter,’ it whispered, low enough for only him to hear. ‘I see you’ve come for another chance. But fate has a funny way of twisting, doesn’t it?’ Harry hesitated, remembering how his choice to be in Gryffindor had set everything in motion. What if he had chosen differently? The hat grinned in his mind. ‘Perhaps this time, I’ll put you where you belong...’ As the feast continued, Harry’s heart raced. He knew that some choices were never meant to be undone, and now the Sorting Hat’s words haunted him. Maybe the real battle was never with Voldemort, but with himself.",
                            DateCreated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 1,
                            Title = "The Sorting Hat's Secret",
                            UserId = 15
                        },
                        new
                        {
                            Id = 2,
                            Content = "The cold metal walls of the starship echoed with each step as Vera checked her blaster. Beside her, Jax smirked. ‘You know, we could’ve walked away from this one.’ ‘And let them take the payout? Not a chance.’ The ship lurched violently as enemy fire hit the hull, and both bounty hunters stumbled but recovered quickly. They were being hunted themselves now. Jax’s hand hovered over the console. ‘We can jump now, or we stay and fight.’ Vera glanced at the radar—a swarm of ships were closing in fast. She didn’t trust Jax, not fully. But trust wouldn’t matter if they didn’t survive the next ten minutes. ‘Jump,’ she said finally, and Jax’s grin widened as the ship slipped into hyperspace, leaving the danger—and perhaps her better judgment—behind.",
                            DateCreated = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 2,
                            Title = "A Bounty Too Far",
                            UserId = 14
                        },
                        new
                        {
                            Id = 3,
                            Content = "It was nearly midnight when the knock came. Emma stirred in bed, unsure if it was part of her dream. The knock came again, soft but insistent. Slowly, she slipped out of bed, heart pounding, and tiptoed to the door. A folded piece of paper slid through the crack at the bottom just as she reached it. She hesitated before picking it up, unfolding the note with shaky hands. ‘Meet me by the river at midnight,’ it read. The handwriting was messy, hurried, almost as if the writer had little time. Emma felt a strange tug in her chest—a feeling she couldn’t quite explain. She threw on her coat and hurried out into the cold night. At the river, she saw him waiting, his violin case slung over his shoulder. ‘You came,’ he whispered, as if he hadn’t believed she would. Emma nodded, her breath visible in the chilly air. And just like that, two lives that had drifted apart began to weave a song only they could hear.",
                            DateCreated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 3,
                            Title = "The Note Beneath the Door",
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            Content = "Detective Blake wasn’t one for mysteries involving kitchenware, but this was no ordinary spoon. ‘It vanished right off the table,’ the witness claimed, eyes wide with disbelief. Blake examined the room, noting the odd layout—too many spoons in the drawer, and one missing from the pristine display. His partner chuckled. ‘You’re really going to crack this one, aren’t you?’ ‘A spoon doesn’t just vanish,’ Blake muttered, crouching down to inspect the floorboards. It was then he noticed a faint groove along the edge—a hidden compartment. With a grin, Blake pried it open, revealing not just the spoon, but a stack of stolen jewels hidden beneath it. ‘Looks like this case just went from silverware to grand theft,’ he said with a smirk, holding up the glittering evidence. His partner shook her head, laughing. ‘Only you could solve a crime like this.’",
                            DateCreated = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 4,
                            Title = "The Case of the Vanishing Spoon",
                            UserId = 12
                        },
                        new
                        {
                            Id = 5,
                            Content = "The ancient throne loomed at the center of the darkened hall, its surface etched with symbols no living soul could decipher. Prince Aldric approached it cautiously, his sword drawn. The old tales warned of the curse: the first heir to sit on the throne would inherit the sins of the past kings. The air was thick with the scent of old incense, and shadows flickered as if alive. ‘There is no turning back,’ he whispered to himself. As Aldric sat, the throne groaned beneath his weight, and a deep, ancient voice echoed through the room. ‘Do you seek power, boy? Or redemption?’ Aldric closed his eyes, knowing that to claim one, he would have to sacrifice the other.",
                            DateCreated = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 5,
                            Title = "The Haunted Throne",
                            UserId = 11
                        },
                        new
                        {
                            Id = 6,
                            Content = "The portal closed with a shimmer, leaving Emily stranded in a realm she did not recognize. The sky above was a swirling canvas of colors, and the ground beneath her felt like it was made of glass. Strange creatures darted through the air, their shapes shifting with every movement. Clutching her pendant, Emily knew it was her only way back—but it flickered weakly, as if the magic within was almost spent. With every step she took deeper into the abyss, the whispers grew louder, urging her to stay. But she couldn’t. She had to find her way home before the last light of the pendant faded forever.",
                            DateCreated = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 6,
                            Title = "Lost in the Abyss",
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            Content = "Amara knew she shouldn’t have come back, but the memories of him haunted her every step. She found Theo waiting at the same café they used to visit as teenagers. Time had aged them both, but the fire in his eyes remained the same. ‘I thought you forgot about me,’ Theo said quietly, stirring his coffee. ‘I tried,’ Amara admitted. ‘But you’re impossible to forget.’ They spent hours talking about everything and nothing, as if the years between them were mere minutes. And when Theo reached for her hand across the table, Amara knew some love stories were meant to start over.",
                            DateCreated = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 7,
                            Title = "A Love Rekindled",
                            UserId = 13
                        },
                        new
                        {
                            Id = 8,
                            Content = "Nina’s fingers hovered over the piano keys, the weight of the unfinished symphony pressing down on her. This was the last song she would ever play for him. With a deep breath, she let the music flow from her heart, each note telling the story of love, loss, and hope. As the melody reached its peak, tears blurred her vision. But she played on, knowing that this was how she would say goodbye. The final chord lingered in the air, a bittersweet farewell to the past and a step toward an unknown future.",
                            DateCreated = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 8,
                            Title = "The Final Melody",
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            Content = "Max had always known that in the corporate world, loyalty was a currency few could afford. But this time, the betrayal came from someone he least expected—his business partner. With the merger on the line, Max found himself at a crossroads: expose the betrayal and risk losing everything, or play along and win the game. He stared at the contract in front of him, knowing that signing it would change his life forever. But sometimes, in the world of high stakes, the only way to win was to lose.",
                            DateCreated = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 9,
                            Title = "The Business of Betrayal",
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            Content = "Dr. Lila Monroe believed in miracles, but she never thought she would be one. Her clinic in the heart of the city served patients no one else wanted. And when a mysterious patient arrived with a condition Lila had never seen, she knew she was about to be tested in ways she never imagined. The man’s fevered words hinted at a story far more dangerous than any disease. And as Lila fought to save his life, she realized that healing wasn’t just about the body—it was about mending hearts, too.",
                            DateCreated = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 10,
                            Title = "Healing Hands",
                            UserId = 11
                        },
                        new
                        {
                            Id = 11,
                            Content = "With nothing but a backpack and a map, Leo set off on an adventure across the world. Every city, every stranger, every road taught him something new about himself. But the journey wasn’t just about seeing new places—it was about finding his way back to the person he used to be. And somewhere between the mountains and the sea, Leo discovered that sometimes, the greatest destination was coming home.",
                            DateCreated = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 11,
                            Title = "Wanderlust",
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            Content = "In a world where political ambition came with a cost, Senator Quinn had always known he would have to pay. But when a secret from his past threatened to ruin everything, he found himself on the brink of losing not only his career but also the people he loved. With the clock ticking, Quinn had to decide: would he cling to power, or would he choose the one thing money couldn’t buy—redemption?",
                            DateCreated = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 12,
                            Title = "The Price of Power",
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            Content = "The crowd roared as Jade crossed the finish line, her heart pounding with triumph. But victory wasn’t just about winning the race—it was about proving to herself that she could. For every mile, every setback, and every doubt, Jade had fought to be here. And as the confetti rained down, she realized that sometimes, the hardest race was the one you ran against yourself.",
                            DateCreated = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 13,
                            Title = "Victory Lap",
                            UserId = 14
                        },
                        new
                        {
                            Id = 14,
                            Content = "The festival was a riot of colors, sounds, and flavors, each booth telling the story of a different culture. For Maya, it was a chance to reconnect with her roots—and with the father she hadn’t seen in years. As they walked through the festival together, sharing food and memories, Maya realized that family wasn’t just about blood—it was about the stories they carried with them.",
                            DateCreated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SaveAsDraft = false,
                            StoryId = 14,
                            Title = "Cultural Mosaic",
                            UserId = 13
                        });
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChapterId = 1,
                            Content = "I love the twist on Harry's choices! It really makes me think about fate.",
                            CreatedOn = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 2,
                            ChapterId = 2,
                            Content = "Vera and Jax have such great chemistry! Can't wait to see what happens next.",
                            CreatedOn = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 3,
                            ChapterId = 3,
                            Content = "The suspense in this chapter is intense! What will Emma do next?",
                            CreatedOn = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            ChapterId = 4,
                            Content = "This mystery is captivating! I can't believe the spoon was hiding jewels!",
                            CreatedOn = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 5,
                            ChapterId = 5,
                            Content = "Aldric's struggle with the throne is fascinating! Will he choose power or redemption?",
                            CreatedOn = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            ChapterId = 6,
                            Content = "Emily's journey through the abyss sounds incredible! I hope she finds her way back.",
                            CreatedOn = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12
                        },
                        new
                        {
                            Id = 7,
                            ChapterId = 7,
                            Content = "Amara and Theo's reunion gives me all the feels! Can't wait for more.",
                            CreatedOn = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 8,
                            ChapterId = 8,
                            Content = "Nina's last performance is heartbreaking! What a way to say goodbye.",
                            CreatedOn = new DateTime(2024, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            ChapterId = 9,
                            Content = "Max's dilemma in the corporate world is so relatable! What a tough choice.",
                            CreatedOn = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13
                        },
                        new
                        {
                            Id = 10,
                            ChapterId = 10,
                            Content = "Dr. Monroe's story is inspiring! Healing goes beyond just physical health.",
                            CreatedOn = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            ChapterId = 11,
                            Content = "Leo's adventure sounds exhilarating! Can't wait to see where it takes him.",
                            CreatedOn = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            ChapterId = 12,
                            Content = "Senator Quinn's struggles with power are gripping! This story has me on edge.",
                            CreatedOn = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            ChapterId = 13,
                            Content = "Jade's victory is so empowering! Love this journey of self-discovery.",
                            CreatedOn = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            ChapterId = 14,
                            Content = "The festival's cultural richness is beautifully portrayed! Great family bonding.",
                            CreatedOn = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 15
                        });
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A time-travel story where Harry returns to his first year to fix everything.",
                            Image = "https://example.com/images/hogwarts.jpg",
                            TargetAudience = "Young Adult",
                            Title = "A Second Chance at Hogwarts",
                            UserId = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            DateCreated = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two rival bounty hunters must work together to survive an intergalactic chase.",
                            Image = "https://example.com/images/galactic.jpg",
                            TargetAudience = "New Adult",
                            Title = "Galactic Refuge",
                            UserId = 14
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateCreated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A romance between a concert violinist and the mysterious pianist next door.",
                            Image = "https://example.com/images/heartstrings.jpg",
                            TargetAudience = "Adult",
                            Title = "Heartstrings",
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 11,
                            DateCreated = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A detective with a love for pranks solves cases with humor.",
                            Image = "https://example.com/images/detective.jpg",
                            TargetAudience = "Young Adult",
                            Title = "The Laughing Detective",
                            UserId = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            DateCreated = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An exiled prince returns to reclaim his haunted castle.",
                            Image = "https://example.com/images/castle.jpg",
                            TargetAudience = "New Adult",
                            Title = "Castle of Shadows",
                            UserId = 11
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            DateCreated = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A group of teenagers discovers a portal to a parallel world.",
                            Image = "https://example.com/images/abyss.jpg",
                            TargetAudience = "Young Adult",
                            Title = "Into the Abyss",
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            DateCreated = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A series of heartwarming meetings at a small-town coffee shop.",
                            Image = "https://example.com/images/cafe.jpg",
                            TargetAudience = "Adult",
                            Title = "Café Encounters",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            DateCreated = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A ghost helps a troubled author find peace through her writing.",
                            Image = "https://example.com/images/whispers.jpg",
                            TargetAudience = "New Adult",
                            Title = "Whispers in the Dark",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 14,
                            DateCreated = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A villain falls in love with the hero sworn to defeat them.",
                            Image = "https://example.com/images/heroes.jpg",
                            TargetAudience = "Young Adult",
                            Title = "Heroes and Villains",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            DateCreated = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Old letters reveal a forgotten love story between two soldiers.",
                            Image = "https://example.com/images/letters.jpg",
                            TargetAudience = "Adult",
                            Title = "Letters from the Past",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DateCreated = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A warrior prepares for a final battle, haunted by visions of the future.",
                            Image = "https://example.com/images/stand.jpg",
                            TargetAudience = "New Adult",
                            Title = "The Last Stand",
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 11,
                            DateCreated = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mix-up at a royal wedding leads to a cascade of hilarious events.",
                            Image = "https://example.com/images/comedy.jpg",
                            TargetAudience = "Young Adult",
                            Title = "Comedy of Errors",
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 12,
                            DateCreated = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Two writers leave coded messages for each other in their novels.",
                            Image = "https://example.com/images/lines.jpg",
                            TargetAudience = "Adult",
                            Title = "Between the Lines",
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            DateCreated = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A secret train only appears to those in need of second chances.",
                            Image = "https://example.com/images/express.jpg",
                            TargetAudience = "Young Adult",
                            Title = "The Midnight Express",
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            DateCreated = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A scientist and an artist explore love across multiple dimensions.",
                            Image = "https://example.com/images/paths.jpg",
                            TargetAudience = "New Adult",
                            Title = "Parallel Paths",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Friendship"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Space"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Betrayal"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Healing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Competition"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Dark Fantasy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "High Stakes"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Self-Discovery"
                        });
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            Image = "https://example.com/images/john.jpg",
                            LastName = "Doe",
                            Uid = "user001",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            Image = "https://example.com/images/jane.jpg",
                            LastName = "Smith",
                            Uid = "user002",
                            Username = "jane_smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            Image = "https://example.com/images/alice.jpg",
                            LastName = "Johnson",
                            Uid = "user003",
                            Username = "alice_johnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            Image = "https://example.com/images/bob.jpg",
                            LastName = "Brown",
                            Uid = "user004",
                            Username = "bob_brown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charlie@example.com",
                            FirstName = "Charlie",
                            Image = "https://example.com/images/charlie.jpg",
                            LastName = "Davis",
                            Uid = "user005",
                            Username = "charlie_davis"
                        },
                        new
                        {
                            Id = 6,
                            Email = "eve@example.com",
                            FirstName = "Eve",
                            Image = "https://example.com/images/eve.jpg",
                            LastName = "Wilson",
                            Uid = "user006",
                            Username = "eve_wilson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "dave@example.com",
                            FirstName = "Dave",
                            Image = "https://example.com/images/dave.jpg",
                            LastName = "Martinez",
                            Uid = "user007",
                            Username = "dave_martinez"
                        },
                        new
                        {
                            Id = 8,
                            Email = "fiona@example.com",
                            FirstName = "Fiona",
                            Image = "https://example.com/images/fiona.jpg",
                            LastName = "Taylor",
                            Uid = "user008",
                            Username = "fiona_taylor"
                        },
                        new
                        {
                            Id = 9,
                            Email = "george@example.com",
                            FirstName = "George",
                            Image = "https://example.com/images/george.jpg",
                            LastName = "Anderson",
                            Uid = "user009",
                            Username = "george_anderson"
                        },
                        new
                        {
                            Id = 10,
                            Email = "hannah@example.com",
                            FirstName = "Hannah",
                            Image = "https://example.com/images/hannah.jpg",
                            LastName = "Thomas",
                            Uid = "user890",
                            Username = "hannah_thomas"
                        },
                        new
                        {
                            Id = 11,
                            Email = "ian@example.com",
                            FirstName = "Ian",
                            Image = "https://example.com/images/ian.jpg",
                            LastName = "Jackson",
                            Uid = "user567",
                            Username = "ian_jackson"
                        },
                        new
                        {
                            Id = 12,
                            Email = "jack@example.com",
                            FirstName = "Jack",
                            Image = "https://example.com/images/jack.jpg",
                            LastName = "White",
                            Uid = "user234",
                            Username = "jack_white"
                        },
                        new
                        {
                            Id = 13,
                            Email = "kathy@example.com",
                            FirstName = "Kathy",
                            Image = "https://example.com/images/kathy.jpg",
                            LastName = "Garcia",
                            Uid = "user789",
                            Username = "kathy_garcia"
                        },
                        new
                        {
                            Id = 14,
                            Email = "liam@example.com",
                            FirstName = "Liam",
                            Image = "https://example.com/images/liam.jpg",
                            LastName = "Martinez",
                            Uid = "user456",
                            Username = "liam_martinez"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mia@example.com",
                            FirstName = "Mia",
                            Image = "https://example.com/images/mia.jpg",
                            LastName = "Hernandez",
                            Uid = "user123",
                            Username = "mia_hernandez"
                        });
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.Property<int>("StoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("StoriesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("StoryTag");
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Chapter", b =>
                {
                    b.HasOne("BE_Fan_Fusion.Models.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Fan_Fusion.Models.User", "User")
                        .WithMany("Chapters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Comment", b =>
                {
                    b.HasOne("BE_Fan_Fusion.Models.Chapter", "Chapter")
                        .WithMany("Comments")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Fan_Fusion.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Story", b =>
                {
                    b.HasOne("BE_Fan_Fusion.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Fan_Fusion.Models.User", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.HasOne("BE_Fan_Fusion.Models.Story", null)
                        .WithMany()
                        .HasForeignKey("StoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Fan_Fusion.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Chapter", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.Story", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("BE_Fan_Fusion.Models.User", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
